export { default as About } from './about/About';
export { default as CTA } from './cta/CTA';
export { default as Footer } from './footer/Footer';
export { default as Gallery } from './gallery/Gallery';
export { default as Pricing } from './pricing/Pricing';
export { default as Services } from './services/Services.jsx';
export { default as Navbar } from './navbar/Navbar.jsx';
export { default as Header } from './header/Header.jsx';
export { default as FAQ } from './faq/FAQ.jsx';